spring:
  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://studio-eye-gold-rds-promotion.c3wm402we7do.ap-northeast-2.rds.amazonaws.com:3306/promotion_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: studioeye
    password: HeapIsGold!!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

aws:
  s3:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: ap-northeast-2
    bucket: ${BUCKET}