name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kimyubi/pp
          stage: main
          yaml: >
            name: promoationpage-server

            app: java@17

            options:
              ports: "8000"
              env:
                - name: ACCESS_KEY
                  value: ${{ secrets.ACCESS_KEY }}
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: SECURITY_USER_NAME
                  value: ${{ secrets.SECURITY_USER_NAME }}
                - name: SECURITY_PASS_WORD
                  value: ${{ secrets.SECURITY_PASS_WORD }}
                - name: SECRET_KEY
                  value: ${{ secrets.SECRET_KEY }}
                - name: BUCKET
                  value: ${{ secrets.BUCKET }}
                - name: DB_URL
                  value: ${{ secrets.DB_URL }}
                - name: DB_USER_NAME
                  value: ${{ secrets.DB_USER_NAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
